name: regression suite
on: 
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
  schedule:
     - cron: '30 2 * * *'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.20'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest -s --html=report.html -self-contained-html
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: report.html
